### ISSUE TITLE
Issues to get started with "Seq2SeqClassificationConsole"

### ISSUE THREAD

**Issue by TodayAI** [zhongkaifu/Seq2SeqSharp#67] opened 2023-04-30 12:30 UTC
I have issues to get started with setting up a demo for the Seq2SeqClassificationConsole app.
I assume as a NewBe I do not setup the training data correctly. Can you please point me the way to setup a demo?

I setup two folders for Traning and Validation
![grafik](https://user-images.githubusercontent.com/132204565/235352600-aee70552-da0f-4672-ad00-49b8bc748e25.png)

In the train folder I placed 2 training files
Train01.CLS.snt
Train01.SRC.snt

In the validate folder I placed 2 training files
Validate01.CLS.snt
Validate01.SRC.snt

This are my command line settings:
-Task Train  -TrainCorpusPath .\Train -ValidCorpusPaths .\Valid -TgtLang CLS -SrcLang SRC -ProcessorType CPU -DecoderType Transformer -EncoderLayerDepth 6 

Error in method BuildVocabs at line "Vocab tgtVocab = tgtVocabs[1];" because tgtVocabs with Index 1 does not exist.

public (Vocab, Vocab, Vocab) BuildVocabs(int srcVocabSize = 45000, int tgtVocabSize = 45000, bool sharedVocab = false)
[...]
(var srcVocabs, var tgtVocabs) = CorpusBatch.GenerateVocabs(srcVocabSize, tgtVocabSize);

            Vocab srcVocab = srcVocabs[0];
            Vocab clsVocab = tgtVocabs[0];
            Vocab tgtVocab = tgtVocabs[1];  // Error position

Content of  Train01.CLS.snt:
What should I do if I have a sore throat and a runny nose? [SEP] I feel sore in my throat after getting up in the morning, and I still have clear water in my nose. I measure my body temperature and I don’t have a fever. Have you caught a cold? What medicine should be taken.
How can I recuperate if my ankle is twisted? [SEP] I twisted my ankle when I went down the stairs, and now it is red and swollen. X-rays were taken and there were no fractures. May I ask how to recuperate to get better as soon as possible.
How to diagnose Alzheimer's Caregiving ? [SEP] Now that your family member or friend has received a diagnosis of Alzheimers disease, its important to learn as much as you can about the disease and how to care for someone who has it. You may also want to know the right way to share the news with family and friends.
What are the treatments for Alzheimer's Caregiving ? [SEP] Currently, no medication can cure Alzheimers disease, but four medicines are approved to treat the symptoms of the disease. - Aricept (donezepil)for all stages of Alzheimers  - Exelon (rivastigmine)for mild to moderate Alzheimers  - Razadyne (galantamine)--for mild to moderate Alzheimers  - Namenda (memantine)for moderate to severe Alzheimers  -  Namzarec (memantine and donepezil)for moderate to severe Alzheimers Aricept (donezepil)for all stages of Alzheimers Exelon (rivastigmine)for mild to moderate Alzheimers Razadyne (galantamine)
How to diagnose Alzheimer's Caregiving ? [SEP] When you learn that someone has Alzheimers disease, you may wonder when and how to tell your family and friends. You may be worried about how others will react to or treat the person. Others often sense that something is wrong before they are told. Alzheimers disease is hard to keep secret. When the time seems right, be honest with family, friends, and others. Use this as a chance to educate them about Alzheimers disease. You can share information to help them understand what you and the person with Alzheimers are going through. You can also tell them what they can do to help.

Content of  Train01.SRC.snt:
Otorhinolaryngology 
Orthopedics 
Alzheimer1 
Alzheimer2 
Alzheimer3

**Comment by zhongkaifu** [comment] 2023-04-30 15:09
Hi @TodayAI ,

It seems your task is to predict tags of input sentences, so you need to use SeqClassificationConsole tool.

For Seq2SeqClassificationConsole tool is used to not only predict tags, but also generate text according to given input sentences. It's a multi-tasks tool.

Thanks
Zhongkai Fu

**Comment by TodayAI** [comment] 2023-04-30 16:30
I want to generate text according to the input sentence. But before I can perform this i must train my model. I do not know how to train "predict tag and generate text according to given inut sentences". I try to rebuilt a demo on your medial question and answer app.

**Comment by zhongkaifu** [comment] 2023-04-30 16:46
My medical Q&A demo (https://huggingface.co/spaces/zhongkaifu/medical_qa_chs) is based on seq2seq model and there is no tags in it. If you want to output both tags and text, you may choose:
1. If you use Seq2SeqClassificationConsole, your target data set should look like "Tags \t Output Text". However, your current target data set (*.SRCsnt) only has Tags, but no output text. This is the reason why you get error "tgtVocabs with Index 1 does not exist."
2. If you use Seq2SeqConsole, you target data set will look like "Tags Output Text".

GPT model only has decoder, so you need to concatenate your input, tag, and output text into a single line (record) for it. For GPT style model, you could use GPTConsole tool for training and test.

**Comment by TodayAI** [comment] 2023-04-30 16:49
Thank you I understand now.
Should I update your documentation once I am done with this?

**Comment by zhongkaifu** [comment] 2023-04-30 16:51
Tags vocabularies are saved into tgtVocabs[0], and output text vocabulary are saved into tgtVocabs[1]

Please go ahead for updates.

**Comment by TodayAI** [comment] 2023-04-30 16:52
Thank you!

**Comment by zhongkaifu** [comment] 2023-04-30 22:12
Good to know it. :)

**Comment by TodayAI** [comment] 2023-05-01 15:18
I have a problem to generate text. It only predicts the classification.
Output.txt:
Otorhinolaryngology	<s>  </s>

I tried differents console setttings:
 -DecoderType Transformer
 -DecoderType GPTDecoder

This are the command line settings:
Seq2SeqClassificationConsole.exe -Task Test -InputTestFile Input.txt -OutputFile Output.txt -OutputPromptFile OutputPrompt.txt -ModelFilePath Seq2Seq.Model -ProcessorType CPU -DecoderType Transformer -DecodingStrategy Sampling -PrimaryTaskId 0 -CompilerOptions --use_fast_math -DecoderLayerDepth 2'

How can I setup the console app "Seq2SeqClassificationConsole" to generate text.

This is are the tags of the "CLS" file:
Otorhinolaryngology 	 Otorhinolaryngology
Orthopedics 	 Orthopedics
Alzheimer 	Alzheimer
Alzheimer 	Alzheimer
Alzheimer 	Alzheimer

This is are the tokens for the predicted category:
What should I do if I have a sore throat and a runny nose? [SEP] I feel sore in my throat after getting up in the morning, and I still have clear water in my nose. I measure my body temperature and I don’t have a fever. Have you caught a cold? What medicine should be taken. 	 A runny nose occurs when mucus drips from the nostrils. Sore throat and runny nose often occur together, such as with a cold, COVID-19 infection, or allergies. A runny nose results from mucus trapping germs or other harmful particles and draining out of the nose, ridding the body of the infection or irritant. A sore throat develops from the inflamed throat tissue and mucus dripping down the back of the throat. Viral infections that cause a sore throat and runny nose.

**Comment by zhongkaifu** [comment] 2023-05-01 16:27
How did you get your model trained, such as data set, iteration you already have ran and others ?  Because text generation needs larger dataset and more iterations during training.

For your test command line, you don't have to specify -OutputPromptFile if you don't have it, and you also don't need to specify -DecoderType, -DecoderLayerDepth, because they are already in your trained model. These parameters are only used for training mode.

I didn't understand your tags of the "CLS" file. Why characters between tab are same ?

For your tokens for the predicted category, it is the text you expect model to output ? Why it includes question and tab[/t] here ?


Can you please explain and share what your task, input data and output data with a few examples, config file and logs for both training and test with me here, and I can understand it clearly.

**Comment by TodayAI** [comment] 2023-05-01 17:23
I attached my demo project.
I hope the info helps to create a working demo for the "Seq2SeqClassificationConsole" that predicts labels and generates text. Any working example will do. With this knoowledge I will suggest an update for your documentation.

Answers for your questions:

1. The CLS file needs two groups. Oherwise an error is thrown:
    (The group size in target sentence is '1', but it should be 2)
    The second group seems not to be used in your code and is not part of the vocabulary.
2. Input.txt contains the prompt for which a category should be predicted and an answer text should be created
3. You wrote: For your tokens for the predicted category, it is the text you expect model to output?
    Yes. In file Train01.SRC.snt the text after Tags \t "Output Text" should be used for generating text. 

[Seq2SeqClassificationConsole.zip](https://github.com/zhongkaifu/Seq2SeqSharp/files/11366817/Seq2SeqClassificationConsole.zip)

**Comment by zhongkaifu** [comment] 2023-05-01 17:56
I just checked your dataset, and it has some format issue there. The *.SRC.snt file should keep questions only, and the *.CLS.snt (I suggest you rename it to TGT.snt) should keep both tag and predicted sentences.  So the correct dataset looks like:

Train01.SRC.snt:
What should I do if I have a sore throat and a runny nose?
How can I recuperate if my ankle is twisted? 

Train01.CLS.snt (CLS is ambiguous, so suggest it to rename to TGT)
Otorhinolaryngology [\t] I feel sore in my throat after getting up in the morning, and I still have clear water in my nose. I measure my body temperature and I don’t have a fever. Have you caught a cold? What medicine should be taken. 	 A runny nose occurs when mucus drips from the nostrils. Sore throat and runny nose often occur together, such as with a cold, COVID-19 infection, or allergies. A runny nose results from mucus trapping germs or other harmful particles and draining out of the nose, ridding the body of the infection or irritant. A sore throat develops from the inflamed throat tissue and mucus dripping down the back of the throat. Viral infections that cause a sore throat and runny nose.
Orthopedics [\t] I twisted my ankle when I went down the stairs, and now it is red and swollen. X-rays were taken and there were no fractures. May I ask how to recuperate to get better as soon as possible. 	 Orthopaedic disorders are the second largest source of disability globally, with low back pain being the single leading cause of disability. Approximately 1.71 billion people have musculoskeletal conditions worldwide. Musculoskeletal conditions can affect people of all ages and most commonly impact those in adolescence and older age. These conditions affect the ability to lead active lives and have a negative effect on economic productivity. The burden of musculoskeletal disease is expected to rise as populations age. These conditions place a considerable strain on sufferers, their carers, and on healthcare systems in general. They also keep large numbers of people from being fully active members of society. Given the demographic challenge of an ageing population, Europe will be particularly impacted by these conditions in the coming years.

The model will build vocabularies from your dataset.

The model trained by Seq2SeqClassificationConsole is an Encoder-Decoder model, so when you run "test", you don't have to specify -DecdoerType, because the tool can get model type from model file. If your question is already in -InputTestFile, you don't need to specify -OutputPromptFile "-OutputPromptFile" is a part of your answer that prompt model to generate the rest of the answer.

If you want to train your model as GPT type model, you need to use GPTConsole tool for both training and test rather than Seq2SeqClassificationConsole, and put all your questions, tags and answers in a single line.

**Comment by zhongkaifu** [comment] 2023-05-02 21:56
For GPT type model, I just simply trained it on a large text corpus using GPTConsole tool.
For your task, the input to your training would looks like as follows (question + tag + answer) before it get tokenized:
How can I recuperate if my ankle is twisted? Otorhinolaryngology I feel sore in my throat after getting up in the morning, and I still have clear water in my nose. I measure my body temperature and I don’t have a fever. Have you caught a cold? What medicine should be taken. A runny nose occurs when mucus drips from the nostrils. Sore throat and runny nose often occur together, such as with a cold, COVID-19 infection, or allergies. A runny nose results from mucus trapping germs or other harmful particles and draining out of the nose, ridding the body of the infection or irritant. A sore throat develops from the inflamed throat tissue and mucus dripping down the back of the throat. Viral infections that cause a sore throat and runny nose.

For test, you just send questions, such as "How can I recuperate if my ankle is twisted?", to the model, and let model to predict the rest of the text.

**Comment by TodayAI** [comment] 2023-05-02 22:47
For the GPTConsole tool I seperate (question + tag + answer) with a tab [/t]?

**Comment by zhongkaifu** [comment] 2023-05-03 04:00
GPTConsole tool doesn't require tabs [/t].

**Comment by TodayAI** [comment] 2023-05-06 05:34
With your suggestions I get the console apps up and running. I am testing on different text corpus. However I needed to make some small changes to data preparation and tokenization.
This weekend I will start to train a large text corpus with my underdog Hardware analog to GPT-2 with OpenWebText. For this I purchased a used Jetson Nano 2GB.
Are you interested that we place my changes to the tokenizer back on your original sources to work out of the box with OpenWebText?

**Comment by zhongkaifu** [comment] 2023-05-06 06:42
> With your suggestions I get the console apps up and running. I am testing on different text corpus. However I needed to make some small changes to data preparation and tokenization.
> 
> This weekend I will start to train a large text corpus with my underdog Hardware analog to GPT-2 with OpenWebText. For this I purchased a used Jetson Nano 2GB.
> 
> Are you interested that we place my changes to the tokenizer back on your original sources to work out of the box with OpenWebText?
> 
> 

Any contribution is always welcome. :) You could send out pull request for it.

Are you going to use Jetson Nano 2GB for training or just for inference ?

**Comment by TodayAI** [comment] 2023-05-06 08:24
Yes, lets work classical with pull requests. Then you can decide if you want to include the suggested code.
I am new to Jetson Nano. In the first step I use it for training.

Can training data of the GPTDecoder use "position embeddings", "segment embeddings", and "tag embeddings"?

You wrote above for the GPTConsole:
For your task, the input to your training would looks like as follows (question + tag + answer)

Does it make sense to use embeddings in the training data? I add because I have a large number of supervised text prompts. Example: How to book a flight to Los Angeles? [Multiple supervised answers... ]

**Comment by zhongkaifu** [comment] 2023-05-06 14:16
> Yes, lets work classical with pull requests. Then you can decide if you want to include the suggested code.
> 
> I am new to Jetson Nano. In the first step I use it for training.
> 
> 
> 
> Can training data of the GPTDecoder use "position embeddings", "segment embeddings", and "tag embeddings"?
> 
> 
> 
> You wrote above for the GPTConsole:
> 
> For your task, the input to your training would looks like as follows (question + tag + answer)
> 
> 
> 
> Does it make sense to use embeddings in the training data? I ask because I have a large number of supervised text prompts. Example: How to book a flight to Los Angeles? [Multiple supervised answers... ]
> 
> 
> 
> I want to use it for prompt engineering and create "seed prompts" to help the GPTDecoder with the correct context to generate an answer.
> 
> 

These embeddings are pretty general and they can be used for any types of models. Segment embeddings and tag embeddings are optional, you can decide if you want to enable or disable them.

The training set could looks like this:
Question1 + Answer1
Question1 + Answer2
...
Question1 + AnswerN
Question2 + Answer1
...
QuestionX + AnswerY

Each question could have the different number of answers.

How large the model you want to train ? I'm afraid that Jetson Nano 2GB may not have enough performance and memory for larger model.

**Comment by TodayAI** [comment] 2023-05-06 17:53
Thank you for the tips on data preparation. I will follow your suggestions.

So the binary modell with all hashes is kept in memory during training. So I will try to train with a virtual linux server with 12 cores and 64 GB RAM for OpenWebText?

**Comment by zhongkaifu** [comment] 2023-05-06 17:58
> Thank you for the tips on data preparation. I will follow your suggestions.
> 
> 
> 
> So the binary modell with all hashes is kept in memory during training. So I will try to train with a virtual linux server with 12 cores and 64 GB RAM for OpenWebText?


It depends on how large your model is. It would be higher efficiency if you could have GPU for training even if it's just RTX series for desktop and gaming.

**Comment by TodayAI** [comment] 2023-05-07 07:05
I will train a large language model (OpenWebText) on RTX. Can I ask some setup questions:

1. How should I handle punctuation in the training data? Should I add spaces? Example:

Yesterday , I went into the city .
Gorge said : " Please help me ! "

- How many layers should I use for Training a GPT lanugage model? 
36 Layers as you used in your GPT demo? GPT-2 uses 12 layers. GPT-3  uses 96 layers.

- I will use this (english) GPT model for fine tuning. Should I use embeddings? How should I setup word embeddings?

**Comment by zhongkaifu** [comment] 2023-05-07 08:12
You need to run tokenizer against your data set at first, such as SentencePiece, and then use tokenized data set for training and test.

The model size (such as the number of layers) you will choose depends on lots of factors, such as the size of your data set, your computing capacity and others.

GPT-2 has many models with different size. 12 layers is GPT-2 small model.
For GPT-3, I don't think your single RTX GPU is able to train it.

I don't understand "I will use this (english) GPT model for fine tuning." Are you going to train a new GPU model from the scratch, or you just fine-tune a public published GPT model  ?

Embedding is built-in the model and you will use (or update) it.

**Comment by TodayAI** [comment] 2023-05-07 13:07
I want to try to built a 12 or 36 layer GPT model with seq2seqSharp on OpenWebText. I will rent the required hardware for this. I know from nanoGPT it needs 38 hours of training for a 12 layer GPT-2 model on one computer mit 8 x A100 graphic units to train a similar model. I assume that your code is more complex and so it will need more training time.

I think that seq2seqSharp offers no function to import an existing model.

I  will use sentencepiece to prepare the training data. I will add spaces in front of all punctuation.

**Comment by zhongkaifu** [comment] 2023-05-07 15:44
Different hyper-parameters could also affect training time a lot, such as batch size, update frequency. You may need to take some time to adjust it.

No, but you could use Microsoft.ML.OnnxRuntime to load existing trained ONNX GPT model from huggingface or somewhere, and export tensors to Seq2SeqSharp.

**Comment by TodayAI** [comment] 2023-05-07 17:11
I rented a windows based gpu server and found a good offer for this. I consider to write a booklet on advanced language models using net/c# based on seq2seqSharp and my own native c# code like the hidden markov. But we should chat about this privately. Because I am part of a crowdy community I might attract Semi professional users that drive you crazy with feature requests. So we need to consider if it is better if I fork a github sub project. Please give it some thoughts.

"you could use Microsoft.ML.OnnxRuntime to load existing trained ONNX GPT model from huggingface or somewhere, and export tensors to Seq2SeqSharp"
-> that's a pretty cool idea! I have a ONNX bert model in pure ml.net up and running.

**Comment by zhongkaifu** [comment] 2023-05-07 21:59
> I rented a windows based gpu server and found a good offer for this. I consider to write a booklet on advanced language models using net/c# based on seq2seqSharp and my own native c# code like the hidden markov. But we should chat about this privately. Because I am part of a crowdy community I might attract Semi professional users that drive you crazy with feature requests. So we need to consider if it is better if I fork a github sub project. Please give it some thoughts.
> 
> 
> 
> "you could use Microsoft.ML.OnnxRuntime to load existing trained ONNX GPT model from huggingface or somewhere, and export tensors to Seq2SeqSharp"
> 
> -> that's a pretty cool idea! I have a ONNX bert model in pure ml.net up and running.
> 
> 
> 
> 

Yes, feel free to fork Seq2SeqSharp. The development mode is pretty flexible and you can choose any way you like. :) 

My email is fuzhongkai@gmail.com We can chat about your book by email.

**Comment by TodayAI** [comment] 2023-05-08 07:01
Ok. I will contact you privately.

**Comment by TodayAI** [comment] 2023-05-08 07:58
Do I understand your code correctly to tokenize the training data?

It reads all available training files and tokenizes the text corpus? This seems not practical on 7 Million training files of OpenWebText. So I need to split the training data on multiple training runs? Is this correct? Will it modify a previously trained model with the newctraining run data?

**Comment by zhongkaifu** [comment] 2023-05-08 18:39
For training, Seq2SeqSharp accepts tokenized data set as input, so you need to choose and call tokenizer for your task. For example: If you use SentencePiece as tokenizer, you need to
1. Train a SentencePiece model or download an existing SentencePiece model
2. Tokenize your raw data set using the above SentencePiece model
3. Send tokenized data set as input to Seq2SeqSharp for trianing

For test, Seq2SeqSharp already integrated SentencePiece APIs, so you could send your raw data set as input to Seq2SeqSharp. You need to specify parameters "SrcSentencePieceModelPath" and "TgtSentencePieceModelPath" to point to SentencePiece models, and then Seq2SeqSharp will use it.

Most GPU memory cost is caused by forward-backward of the model and weights update. Training data are not kept in GPU memory expect current mini-batch, so splitting the training data won't help for it unless main memory and GPU memory are shared, such as Nvidia Jetson

For your examples, they look good if the model is used for "questions and answers" task.
Again, you need to tokenize them before using them as input for training

**Comment by TodayAI** [comment] 2023-05-09 05:17
The process to train a gpt-2 model is well known. [For details see here](https://wandb.ai/bkkaggle/lm-finetuning/reports/Pretraining-a-124-M-Parameter-GPT-2-Language-Model--VmlldzoyMjg4NzA) 

I try to figure out how to setup the gptConsole to replicate a gpt-2 model on OpenWebText with seq2seqsharp. From your comments I learned so far:

**1. Setup the training data**
All 7 million text files need to be trained in one training run. GPTConsole will not eat up 6 GB GPU RAM, as with trsining a default gpt-2 model  because it feeds the GPU with chunks of data. The reason is propablely that the complete vocabulary needs to be known on training. It is not known if I can split the training into multiple runs when I feed the full vocabulary to seq2seqSharp?

**2. Training parameters**
Can be used as in other gpt-2 models.

**3. Training time duration**
No infos available so far on training OpenWebText on special hardware.

**4. Data setup for fine tuning a pre-trained gpt-2 model**
The data setup for fine tuning a "question and answer" dataset for a pre-trained gpt-2 model is described above.

If it is possible to fine tune a pre-trained gpt-2 model is not known? 
It is little confusing for me that it seems not possible to spilt up training into multiple runs one after another. Generally it should be possible to train data chunks in multiple training runs when the text corpus chunks are of  equal generalization quality as the other text chunks.

**Comment by TodayAI** [comment] 2023-05-10 10:44
Thank you very much. That's a good starting point.

**Closed** 2023-06-06 22:15 UTC
